"""
Message processing utilities for AutoGen agents.

Handles message building and content extraction for LLM conversations.
"""

from typing import Any, List, Optional

from autogen_core.models import SystemMessage, UserMessage


def build_message_sequence(prompt: str, system_prompt: Optional[str] = None) -> List[Any]:
    """
    Build a sequence of messages for the conversation with the LLM.

    :param prompt: The user prompt to process.
    :param system_prompt: Optional system prompt to provide context.
    :return: A list of message objects.
    """
    messages = []
    if system_prompt:
        messages.append(SystemMessage(content=system_prompt))
    messages.append(UserMessage(content=prompt, source="user"))
    return messages


def extract_content(response: Any) -> str:
    """
    Extract the content from a response object.

    :param response: The response from the LLM.
    :return: The content as a string.
    """
    if not response:
        return "No response generated by the LLM."

    # Check if the response has a content attribute (AutoGen 0.5.x API)
    if hasattr(response, "content"):
        if isinstance(response.content, str):
            return response.content
        else:
            # Not a string, convert to string (could be a list or other type)
            return str(response.content)

    # Fall back to string representation
    return str(response)
