"""
Alert Display Tools - FunctionTool wrappers for position alerts.

Issue #433/#458: Extract alert display commands from cli_session.py.

These tools handle:
- Checking current position alerts
- Viewing alert history
- Getting alert severity and details

Note: Alerts are generated by the PositionTracker based on price movements
relative to stop/target levels.
"""

import logging
from typing import Any, Dict, List

from autogen_core.tools import FunctionTool

logger = logging.getLogger(__name__)


# =============================================================================
# Helper Functions
# =============================================================================


def _get_trading_cycle():
    """
    Get CostEfficientTradeCycle instance.

    Returns singleton or creates new instance.
    """
    try:
        from src.trading.scheduling.trading_cycle import CostEfficientTradeCycle

        return CostEfficientTradeCycle()
    except Exception as e:
        logger.error(f"Failed to get trading cycle: {e}")
        return None


def _format_alert(alert: Any) -> Dict[str, Any]:
    """
    Format a PositionAlert object to dict.

    Args:
        alert: PositionAlert object or dict

    Returns:
        Formatted alert dict
    """
    if hasattr(alert, "to_dict"):
        return alert.to_dict()
    elif isinstance(alert, dict):
        return alert
    else:
        # Try to extract common attributes
        return {
            "ticker": getattr(alert, "ticker", "unknown"),
            "alert_type": str(getattr(alert, "alert_type", "unknown")),
            "current_price": getattr(alert, "current_price", 0),
            "severity": getattr(alert, "severity", "INFO"),
            "details": getattr(alert, "details", {}),
            "timestamp": str(getattr(alert, "timestamp", "")),
        }


# =============================================================================
# FunctionTool Wrapper Functions
# =============================================================================


def check_alerts() -> Dict[str, Any]:
    """
    Check current position alerts.

    Fetches current broker state and checks each position for
    alerts (approaching stop/target, profit zones, etc.).

    Returns:
        Dict with:
        - status: "success", "no_alerts", or "error"
        - alerts: List of current alert dicts
        - alert_count: Number of alerts
        - positions_monitored: Number of positions being tracked
    """
    try:
        trading_cycle = _get_trading_cycle()
        if not trading_cycle:
            return {"status": "not_initialized", "message": "Trading cycle not available"}

        if not hasattr(trading_cycle, "position_tracker"):
            return {"status": "not_initialized", "message": "Position tracker not available"}

        # Fetch current broker state
        try:
            broker_state = trading_cycle.fetch_broker_state()
        except Exception as e:
            logger.warning(f"Failed to fetch broker state: {e}")
            broker_state = {}

        # Check alerts
        position_tracker = trading_cycle.position_tracker
        alerts = position_tracker.check_alerts(broker_state)

        if not alerts:
            return {
                "status": "no_alerts",
                "alerts": [],
                "alert_count": 0,
                "positions_monitored": len(position_tracker.positions),
                "message": "No active alerts",
            }

        # Format alerts
        formatted_alerts = [_format_alert(a) for a in alerts]

        # Group by severity
        by_severity: Dict[str, List] = {"CRITICAL": [], "WARNING": [], "INFO": []}
        for alert in formatted_alerts:
            severity = alert.get("severity", "INFO")
            if severity in by_severity:
                by_severity[severity].append(alert)

        return {
            "status": "success",
            "alerts": formatted_alerts,
            "alert_count": len(alerts),
            "positions_monitored": len(position_tracker.positions),
            "by_severity": {k: len(v) for k, v in by_severity.items() if v},
        }

    except Exception as e:
        logger.error(f"Error checking alerts: {e}", exc_info=True)
        return {"status": "error", "error": str(e)}


def get_alert_history(limit: int = 10) -> Dict[str, Any]:
    """
    Get recent alert history.

    Args:
        limit: Maximum alerts to return (default 10)

    Returns:
        Dict with:
        - status: "success" or "error"
        - history: List of historical alert dicts
        - total_alerts: Total alerts in history
    """
    try:
        trading_cycle = _get_trading_cycle()
        if not trading_cycle:
            return {"status": "not_initialized", "message": "Trading cycle not available"}

        if not hasattr(trading_cycle, "position_tracker"):
            return {"status": "not_initialized", "message": "Position tracker not available"}

        position_tracker = trading_cycle.position_tracker
        history = position_tracker.get_alert_history()

        if not history:
            return {
                "status": "success",
                "history": [],
                "total_alerts": 0,
                "message": "No alert history",
            }

        # Format and limit
        formatted = [_format_alert(a) for a in history]
        formatted = formatted[:limit]

        return {
            "status": "success",
            "history": formatted,
            "total_alerts": len(history),
            "returned": len(formatted),
        }

    except Exception as e:
        logger.error(f"Error getting alert history: {e}", exc_info=True)
        return {"status": "error", "error": str(e)}


def get_position_alert_status(ticker: str) -> Dict[str, Any]:
    """
    Get alert status for a specific position.

    Args:
        ticker: Stock ticker symbol

    Returns:
        Dict with:
        - status: "success", "not_found", or "error"
        - ticker: The requested ticker
        - position_status: Current position status
        - recent_alerts: Recent alerts for this position
        - current_levels: Stop/target levels if available
    """
    try:
        trading_cycle = _get_trading_cycle()
        if not trading_cycle:
            return {"status": "not_initialized", "message": "Trading cycle not available"}

        if not hasattr(trading_cycle, "position_tracker"):
            return {"status": "not_initialized", "message": "Position tracker not available"}

        ticker_upper = ticker.upper()
        position_tracker = trading_cycle.position_tracker

        # Find positions matching this ticker
        matching_positions = [
            (pid, pos)
            for pid, pos in position_tracker.positions.items()
            if pos.ticker == ticker_upper
        ]

        if not matching_positions:
            return {
                "status": "not_found",
                "ticker": ticker_upper,
                "message": f"No tracked position for {ticker_upper}",
            }

        # Get the most recent position
        position_id, position = matching_positions[-1]

        # Get alerts for this position
        position_alerts = [
            _format_alert(a) for a in position.alert_history if hasattr(position, "alert_history")
        ]

        return {
            "status": "success",
            "ticker": ticker_upper,
            "position_id": position_id,
            "position_status": position.status,
            "entry_price": position.entry_price,
            "quantity": position.quantity,
            "stop_loss_price": position.stop_loss_price,
            "take_profit_price": position.take_profit_price,
            "recent_alerts": position_alerts[-5:],  # Last 5 alerts
            "total_alerts": len(position_alerts),
        }

    except Exception as e:
        logger.error(f"Error getting alert status for {ticker}: {e}", exc_info=True)
        return {"status": "error", "ticker": ticker, "error": str(e)}


def get_monitored_positions_count() -> Dict[str, Any]:
    """
    Get count of positions being monitored for alerts.

    Returns:
        Dict with:
        - status: "success" or "error"
        - active_positions: Number of active positions
        - total_tracked: Total positions in tracker (including closed)
    """
    try:
        trading_cycle = _get_trading_cycle()
        if not trading_cycle:
            return {"status": "not_initialized", "message": "Trading cycle not available"}

        if not hasattr(trading_cycle, "position_tracker"):
            return {"status": "not_initialized", "message": "Position tracker not available"}

        position_tracker = trading_cycle.position_tracker
        all_positions = position_tracker.positions

        active = sum(1 for p in all_positions.values() if p.status == "ACTIVE")
        closed = sum(1 for p in all_positions.values() if p.status != "ACTIVE")

        return {
            "status": "success",
            "active_positions": active,
            "closed_positions": closed,
            "total_tracked": len(all_positions),
        }

    except Exception as e:
        logger.error(f"Error getting monitored positions count: {e}", exc_info=True)
        return {"status": "error", "error": str(e)}


# =============================================================================
# Display Functions (Issue #459)
# =============================================================================


def show_alerts() -> str:
    """Display current position alerts with formatted output."""
    result = check_alerts()
    if result["status"] == "not_initialized":
        return "❌ Alert system not initialized"
    if result["status"] == "error":
        return f"❌ Error: {result.get('error', 'Unknown')}"
    if result["status"] == "no_alerts":
        return (
            f"✅ No active alerts\n📊 Monitoring {result.get('positions_monitored', 0)} position(s)"
        )

    lines = [f"🚨 Position Alerts ({result['alert_count']})", ""]
    for alert in result.get("alerts", []):
        severity = alert.get("severity", "INFO")
        emoji = "🔴" if severity == "CRITICAL" else "🟡" if severity == "WARNING" else "ℹ️"
        lines.append(
            f"{emoji} {alert.get('ticker', '?')}: {alert.get('alert_type', 'unknown')} @ ${alert.get('current_price', 0):.2f}"
        )
        for key, value in alert.get("details", {}).items():
            lines.append(f"   • {key}: {value}")

    history_result = get_alert_history(limit=5)
    if history_result.get("history"):
        lines.extend(["", f"📜 Recent History ({len(history_result['history'])})"])
        for hist in history_result["history"]:
            lines.append(f"   {hist.get('ticker')}: {hist.get('alert_type')}")
    return "\n".join(lines)


# =============================================================================
# FunctionTool Registration
# =============================================================================


show_alerts_tool = FunctionTool(
    func=show_alerts,
    name="show_alerts",
    description="Display current position alerts with formatted output.",
)

check_alerts_tool = FunctionTool(
    func=check_alerts,
    name="check_alerts",
    description="Check current position alerts including approaching stop/target and profit zones.",
)

get_alert_history_tool = FunctionTool(
    func=get_alert_history,
    name="get_alert_history",
    description="Get recent alert history with timestamps and details.",
)

get_position_alert_status_tool = FunctionTool(
    func=get_position_alert_status,
    name="get_position_alert_status",
    description="Get alert status and stop/target levels for a specific ticker.",
)

get_monitored_positions_count_tool = FunctionTool(
    func=get_monitored_positions_count,
    name="get_monitored_positions_count",
    description="Get count of positions being monitored for alerts.",
)


# Export list for CLI tools registry
CLI_ALERT_TOOLS = [
    show_alerts_tool,
    check_alerts_tool,
    get_alert_history_tool,
    get_position_alert_status_tool,
    get_monitored_positions_count_tool,
]

__all__ = [
    # Display Functions
    "show_alerts",
    # Data Functions
    "check_alerts",
    "get_alert_history",
    "get_position_alert_status",
    "get_monitored_positions_count",
    # FunctionTools
    "CLI_ALERT_TOOLS",
    "check_alerts_tool",
    "get_alert_history_tool",
    "get_position_alert_status_tool",
    "get_monitored_positions_count_tool",
]
